# Generated by Django 2.2.8 on 2020-02-07 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_passenger_flight_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='adult',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='child',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='infant',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_one_way',
        ),
        migrations.AddField(
            model_name='booking',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='flight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Flight'),
        ),
    ]
