# Generated by Django 2.2.8 on 2020-02-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200208_0228'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bookitems', models.ManyToManyField(to='core.Booking')),
            ],
        ),
    ]
