# Generated by Django 2.2.8 on 2020-02-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200210_0750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quantity',
            new_name='adults',
        ),
        migrations.AddField(
            model_name='cart',
            name='kids',
            field=models.IntegerField(default=0),
        ),
    ]
