# Generated by Django 2.2.8 on 2020-02-12 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200212_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='adults',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='kids',
        ),
    ]
